# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#target-branch
version: 2
updates:
  - allow:
      - dependency-type: "direct"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    package-ecosystem: composer
    schedule:
      interval: weekly
    versioning-strategy: "lockfile-only"
    groups:
      symfony:
        dependency-type: "production"
        patterns:
        - "symfony/*"
      prod-dependencies:
        dependency-type: "production"
        exclude-patterns:
        - "symfony/*"
      dev-dependencies:
        dependency-type: "development"
