services:
  deptrac:
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=deptrac
      - COMPOSER_CACHE_DIR=/var/www/deptrac/.cache/composer
    volumes:
      - ./:/var/www/deptrac
      - composer-data:/var/www/deptrac/.cache/composer
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host-gateway}

volumes:
  composer-data:
